### ISSUE TITLE
Very nice

### ISSUE THREAD

**Issue by 007revad** [technorabilia/syno-extract-system-patch#1]
In your readme you should probably change the `docker ...` commands to `sudo docker ...` otherwise everything ends up in /root if the commands are run as root. The docker commands fail without sudo when run by a user.

If people start filling /root with files they could cause a DSM update to fail do to not enough space on the system partition.

**Comment by technorabilia** [comment]
I appreciate you bringing this to my attention.

The non-root account I am using has the necessary permissions to access Docker so I didn't realize this.

**Comment by igorpupkinable** [comment]
> In your readme you should probably change the `docker ...` commands to `sudo docker ...` otherwise everything ends up in /root if the commands are run as root. The docker commands fail without sudo when run by a user.
> 
> If people start filling /root with files they could cause a DSM update to fail do to not enough space on the system partition.

NO, you should never use `sudo docker ...` unless absolutely necessary. It is not as safe at the end.
It is better to fix your setup by adding your user to _docker_ group as per Docker installation docs.

Everything works just fine without `sudo` if Docker configuration is correct.

**Comment by 007revad** [comment]
I'm not a docker expert, but according to the [Docker post-installation doc](https://docs.docker.com/engine/install/linux-postinstall/) adding a user to the docker group grants them root privileges so it's no safer than `sudo docker.`  Unless I'm misunderstanding something.

```
Warning
The docker group grants root-level privileges to the user.
```

**Comment by igorpupkinable** [comment]
@007revad there were changes in recent Docker versions to encourage [rootless mode](https://docs.docker.com/engine/security/rootless/) instead. However, _docker_ group was the default setup without any red warnings in the docs a year or so ago, but things have changed as far as I can see.

I would need to reconfigure my Docker and try this again in rootless mode.
