### ISSUE TITLE
Is there any way to extract patch files?

### ISSUE THREAD

**Issue by imnuke** [technorabilia/syno-extract-system-patch#2]
Nice work! It works fine with `7.1.1-42962-1_DSM_DS220+_42962.pat`. 

But it fails to extract patch files such as `7.1.1-42962-2_synology_geminilake_220+.pat`, which in older versions was a tarball containing some deb packages.

```
$ syno_extract_system_patch data/7.1.1-42962-2_synology_geminilake_220+.pat data/extracted_42926-2
$ echo $?
255
```

Is there any way to extract these patches?

**Comment by solred** [comment]
If I understand correctly you are saying that patch files cannot be extracted using the tool?

![image](https://github.com/technorabilia/syno-extract-system-patch/assets/110088749/f795a17a-8260-4244-9925-aacb860e4752)

**Comment by imnuke** [comment]
Yes. Files in your green box can be extracted using the tool, but files in red box cannot be extracted.

```
$ file 6.2.4-25556-4_synology_geminilake_220+.pat
6.2.4-25556-4_synology_geminilake_220+.pat: gzip compressed data, was "synology_geminilake_220+.pat", last modified: Wed Jan 26 15:25:08 2022, max compression, original size modulo 2^32 49520640

$ file 7.1.1-42962-2_synology_geminilake_220+.pat
7.1.1-42962-2_synology_geminilake_220+.pat: data

$ xxd 7.1.1-42962-2_synology_geminilake_220+.pat | head -n 2
00000000: d2ad beef 4502 0000 95c4 2047 31ed 94ae  ....E..... G1...
00000010: 4d27 d492 2a18 eecf 352a ea1f d366 60f3  M'..*...5*...f`.

$ tar -tvf 6.2.4-25556-4_synology_geminilake_220+.pat
-rwxr-xr-x root/root      2342 2021-03-30 16:47 selfcheck-cu01_6.2-25556-s1_all.deb            
-rwxr-xr-x root/root      4668 2021-03-30 16:47 lnxsdk-geminilake-bin_6.2-25556-s1_all.deb     
-rwxr-xr-x root/root  15216186 2021-08-28 05:24 flashupdate_6.2-25556-s2_all.deb                      
-rwxr-xr-x root/root     14970 2021-08-28 05:24 selfcheck-cu02_6.2-25556-s2_all.deb    
-rwxr-xr-x root/root     75082 2021-08-28 05:24 modelfiles_6.2-25556-s2_all.deb
...

$ tar -tvf 7.1.1-42962-2_synology_geminilake_220+.pat
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

For old versions such as 6.x.x it's just a tarball and I can just extract with `tar -xvf`, but for new versions I don't know how to extract them, I don't know what has been changed.

**Comment by technorabilia** [comment]
Thank you for bringing this up - it's a great question. Unfortunately, I don't know the answer.

Sorry about that.

**Comment by geimist** [comment]
> For old versions such as 6.x.x it's just a tarball and I can just extract with `tar -xvf`, but for new versions I don't know how to extract them, I don't know what has been changed.

This can be transferred 1:1 to SPK packages (at least official ones from Synology).

**Comment by imnuke** [comment]
> > For old versions such as 6.x.x it's just a tarball and I can just extract with `tar -xvf`, but for new versions I don't know how to extract them, I don't know what has been changed.
> 
> This can be transferred 1:1 to SPK packages (at least official ones from Synology).

Thanks! But how can I convert the pat file to SPK packages? Are there any tools to extract them?

**Comment by geimist** [comment]
> Thanks! But how can I convert the pat file to SPK packages? Are there any tools to extract them?

I just wanted to point out the parallel with SPK packages. It makes no sense to convert a PAT to an SPK.
